#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/config.toml
LOGS_DIR="/config/logs"

# check if logs folder exists and create it
if [[ ! -d "$LOGS_DIR" ]]; then
  install -dm755 -o $PUID -g $PGID "$LOGS_DIR"
fi

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="$(mktemp)"
  cat <<EOF >"$TMP_FILE"
logLevel = "INFO"
sessionSecret = "$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)"
EOF

  install -m644 -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/autobrr --config=/config
